### ISSUE TITLE
新版本编辑器打开项目后出现编译错误的情况

### ISSUE THREAD

**Issue by jk4517072** [redengineer/redmini#1497]
## Issue类型
bug

## 问题模块
小程序开发者工具(IDE)

## 所属的服务商
相约旅游报名

## 平台
IDE

## 小红书开发者工具版本
2.1.0

## 基础库版本
v3.106.1

## 发生问题的时间
2024-09-12 23:05:23 至 2024-09-12 23:05:23

## 问题描述
升级新版本的小程序开发工具后，出现如下报错。使用的的是新版编译器,没有开启基础库2.0架构编译。开启基础2.0架构编译后能正常编译。新版的扫码登录目前也登录不上了，扫码后没有反应。
![微信截图_20240912231321](https://github.com/user-attachments/assets/e10a9698-c634-47b3-9e94-032b81a45ce8)

Error: Cannot find module &#x27;prettier&#x27;
Require stack:
- C:\Program Files\@xhsmp-ide\resources\extensions\prettier-vscode\dist\extension.js
- C:\Program Files\@xhsmp-ide\resources\app\extension\index.jsError: Cannot find module &#x27;prettier&#x27;
Require stack:
- C:\Program Files\@xhsmp-ide\resources\extensions\prettier-vscode\dist\extension.js
- C:\Program Files\@xhsmp-ide\resources\app\extension\index.js
	at Function._resolveFilename (node:internal/modules/cjs/loader:1084:15)
	at node:internal/modules/cjs/loader:929:27
	at Function.&lt;anonymous&gt; (node:electron/js2c/asar_bundle:2:13327)
	at e._load (/C:/Program%20Files/@xhsmp-ide/resources/app/renderer/windows/project-main/C:\Program Files\@xhsmp-ide\resources\app\extension\index.js:2:617351)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Object.prettier (/C:/Program%20Files/@xhsmp-ide/resources/app/renderer/windows/project-main/C:\Program Files\@xhsmp-ide\resources\extensions\prettier-vscode\dist\extension.js:6234:18)
	at __webpack_require__ (/C:/Program%20Files/@xhsmp-ide/resources/app/renderer/windows/project-main/C:\Program Files\@xhsmp-ide\resources\extensions\prettier-vscode\dist\extension.js:6368:41)
	at ./src/ModuleResolver.ts (/C:/Program%20Files/@xhsmp-ide/resources/app/renderer/windows/project-main/C:\Program Files\@xhsmp-ide\resources\extensions\prettier-vscode\dist\extension.js:263:18)
	at __webpack_require__ (/C:/Program%20Files/@xhsmp-ide/resources/app/renderer/windows/project-main/C:\Program Files\@xhsmp-ide\resources\extensions\prettier-vscode\dist\extension.js:6368:41)
	at /C:/Program%20Files/@xhsmp-ide/resources/app/renderer/windows/project-main/C:\Program Files\@xhsmp-ide\resources\extensions\prettier-vscode\dist\extension.js:6389:26
	at /C:/Program%20Files/@xhsmp-ide/resources/app/renderer/windows/project-main/C:\Program Files\@xhsmp-ide\resources\extensions\prettier-vscode\dist\extension.js:6435:3
	at Object.&lt;anonymous&gt; (/C:/Program%20Files/@xhsmp-ide/resources/app/renderer/windows/project-main/C:\Program Files\@xhsmp-ide\resources\extensions\prettier-vscode\dist\extension.js:6438:12)
	at Module._compile (node:internal/modules/cjs/loader:1271:14)
	at Object..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at node:internal/modules/cjs/loader:967:12
	at Function.&lt;anonymous&gt; (node:electron/js2c/asar_bundle:2:13327)
	at e._load (/C:/Program%20Files/@xhsmp-ide/resources/app/renderer/windows/project-main/C:\Program Files\@xhsmp-ide\resources\app\extension\index.js:2:617351)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at t.default.activateExtension (/C:/Program%20Files/@xhsmp-ide/resources/app/renderer/windows/project-main/C:\Program Files\@xhsmp-ide\resources\app\extension\index.js:2:618749)
error @ index.js:2

## 期望结果
请问开启基础库2.0架构编译,编译的程序是否会出现线上无法打开的情况。

## 重现步骤和复现问题的最小demo Github链接
1.重写编译个工程，用新版ide打开就报错了

**Comment by hhuwc** [comment]
取消勾选 开启2.0 架构编译页面是否能正常展示呢？

**Comment by yujon** [comment]
用运行时2.0架构线上也可以正常运行。prettier这个报错不影响，看看下面是否有其他报错呢

**Comment by jk4517072** [comment]
取消勾选 开启2.0 架构编译页面是否能正常展示呢？
不能

**Comment by jk4517072** [comment]
![image](https://github.com/user-attachments/assets/21c9212a-6322-4127-b604-3089cf1b5388)
![image](https://github.com/user-attachments/assets/101e0a12-f4da-4e51-9a61-bdfd7e400f5c)
![image](https://github.com/user-attachments/assets/23aa1146-e98f-48fb-8abd-103a659febba)

**Comment by jk4517072** [comment]
用的vue3+ts+pinia
![image](https://github.com/user-attachments/assets/01463420-afca-446b-b5ad-fdc3f954b3da)

**Comment by yujon** [comment]
问题已修复，我们发个新的修复包，今天可以升级下

**Comment by jk4517072** [comment]
> 问题已修复，我们发个新的修复包，今天可以升级下

没看到呢，在哪下载

**Comment by yujon** [comment]
> > 问题已修复，我们发个新的修复包，今天可以升级下
> 
> 没看到呢，在哪下载

https://miniapp.xiaohongshu.com/docs?path=/docs/ide/overview
2.1.1
