### ISSUE TITLE
小程序商品-获取信息接口报错

### ISSUE THREAD

**Issue by houleeway** [redengineer/redmini#467]
## 系统环境(必填[多选]) +
- [x] IOS +
- [ ] Android +
- [x] IDE +

## 问题模块(必填[单选]) +
- [ ] 小程序框架 +
- [ ] 小程序Api +
- [ ] 小程序基础组件 +
- [ ] 小程序开发者工具(IDE) +
- [ ] 小程序容器(iOS) +
- [ ] 小程序容器(Android) +
- [x] 小程序服务(服务后台) +
- [ ] 小程序服务(文档平台) +
- [ ] 小程序业务(需求/支付/服务号) +
+
## 服务商名称(必填[单选]) - 排名不分先后 +
- [ ] 有赞 +
- [ ] 微盟 +
- [ ] 直客通 +
- [ ] 民宿宝 +
- [ ] 订单来了 +
- [ ] 太目 +
- [x] 其他(自开发) +
- [ ] 雅诗兰黛 +
- [ ] 迪奥 +
- [ ] 珑骧 +
- [ ] 领克 +
- [ ] 猫眼 +
- [ ] 自我游 +
- [ ] 德比 +
 +
## 基础库版本或小红书APP版本(必填) +
v7.65.1 +
 +
## 重现步骤 和 复现问题的最小demo Github链接 +
问题描述：在商品-获取信息接口中，为了删除一个商品测试数据，对其查看详情和删除操作，都报500错误。但查询商品列表时，能正常查询到。
out_product_id:1594977617244319755
代码中测试数据截图
https://holyv.oss-cn-hangzhou.aliyuncs.com/%E6%B5%8B%E8%AF%95%E6%95%B0%E6%8D%AE%E6%88%AA%E5%9B%BE.png?Expires=1670571525&OSSAccessKeyId=TMP.3Kf1FGkKVCwdMiqMGAV4GNbxnxSwHQ4qWrmC75uZeRXp58rM2YWDLPyx2CfWZe9gMYSXUbNV54R41bekeaxNUqQCc53XV9&Signature=qip7Fo91T4aCPb2JHC9JQwJUQmY%3D

小程序前端截图
https://holyv.oss-cn-hangzhou.aliyuncs.com/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%AB%AF%E6%88%AA%E5%9B%BE.jpeg?Expires=1670571337&OSSAccessKeyId=TMP.3Kf1FGkKVCwdMiqMGAV4GNbxnxSwHQ4qWrmC75uZeRXp58rM2YWDLPyx2CfWZe9gMYSXUbNV54R41bekeaxNUqQCc53XV9&Signature=iLrnSvrC2vOGdIVkDZShZhtHSoo%3D +
 +
## 期望结果 和 实际结果(必填) +
删去该测试商品数据 +
 +
## 补充(猜测可能的原因是什么，你有啥想法，选填) +
小程序bug？

**Comment by houleeway** [comment]
含有报错的日志：
2022-12-09 20:49:20.405 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] ---> POST https://miniapp.xiaohongshu.com/api/rmp/token HTTP/1.1
2022-12-09 20:49:20.405 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] Content-Length: 80
2022-12-09 20:49:20.405 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] Content-Type: application/json
2022-12-09 20:49:20.405 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] 
2022-12-09 20:49:20.405 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] {"appid":"635a8a86cbe21a00013679c5","secret":"e2a584fad5aaa381b166dd04fbf3d02d"}
2022-12-09 20:49:20.405 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] ---> END HTTP (80-byte body)
2022-12-09 20:49:20.478 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] <--- HTTP/1.1 200 OK (73ms)
2022-12-09 20:49:20.479 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] cat-msg-id: openapiminiapp-ac1977b2.0062704-464052-6233
2022-12-09 20:49:20.479 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] cat-msg-id: karen-gateway-s123public-ac1f17d2.64218-464052-3916068
2022-12-09 20:49:20.479 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] connection: keep-alive
2022-12-09 20:49:20.480 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] content-type: application/json;charset=UTF-8
2022-12-09 20:49:20.480 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] date: Fri, 09 Dec 2022 12:49:20 GMT
2022-12-09 20:49:20.480 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] request-id: df7a79063f2c4922831bc81d0f19b5aa
2022-12-09 20:49:20.480 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] transfer-encoding: chunked
2022-12-09 20:49:20.480 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] via: kong/1.2.1
2022-12-09 20:49:20.480 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] x-kong-proxy-latency: 3
2022-12-09 20:49:20.481 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] x-kong-upstream-latency: 20
2022-12-09 20:49:20.481 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] 
2022-12-09 20:49:20.482 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] {"data":{"access_token":"10e37f897cce44a884a2eb15616a2682","expire_in":7199},"success":true,"msg":"success","code":0}
2022-12-09 20:49:20.483 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#token] <--- END HTTP (117-byte body)
2022-12-09 20:49:20.487 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] ---> POST https://miniapp.xiaohongshu.com/api/rmp/mp/deal/product/get?appid=635a8a86cbe21a00013679c5&access_token=10e37f897cce44a884a2eb15616a2682 HTTP/1.1
2022-12-09 20:49:20.487 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] Content-Length: 40
2022-12-09 20:49:20.488 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] Content-Type: application/json
2022-12-09 20:49:20.488 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] 
2022-12-09 20:49:20.488 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] {"out_product_id":"1594977617244319755"}
2022-12-09 20:49:20.488 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] ---> END HTTP (40-byte body)
2022-12-09 20:49:20.546 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] <--- HTTP/1.1 500 Internal Server Error (58ms)
2022-12-09 20:49:20.546 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] cat-msg-id: openapiminiapp-ac1977b2.0062704-464052-6234
2022-12-09 20:49:20.546 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] cat-msg-id: karen-gateway-s123public-ac19c009.64218-464052-3916078
2022-12-09 20:49:20.546 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] connection: keep-alive
2022-12-09 20:49:20.546 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] content-type: application/json;charset=UTF-8
2022-12-09 20:49:20.546 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] date: Fri, 09 Dec 2022 12:49:20 GMT
2022-12-09 20:49:20.546 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] request-id: 9fd4241f23d94695a3847f0005c2931f
2022-12-09 20:49:20.546 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] transfer-encoding: chunked
2022-12-09 20:49:20.546 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] via: kong/1.2.1
2022-12-09 20:49:20.546 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] x-kong-proxy-latency: 3
2022-12-09 20:49:20.547 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] x-kong-upstream-latency: 27
2022-12-09 20:49:20.547 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] 
2022-12-09 20:49:20.547 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] {"error_code":500,"error_msg":"Request failed, please contact our system administrator 请求失败, 请和系统管理人员联系","success":false}
2022-12-09 20:49:20.547 DEBUG 2452 --- [io-8080-exec-10] c.g.t.h.feign.XiaohongshuFeignProvider   : [XiaohongshuFeignProvider#productGet] <--- END HTTP (149-byte body)
2022-12-09 20:49:20.548 ERROR 2452 --- [io-8080-exec-10] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/tm-admin] threw exception [Request processing failed; nested exception is feign.FeignException$InternalServerError: [500 Internal Server Error] during [POST] to [https://miniapp.xiaohongshu.com/api/rmp/mp/deal/product/get?appid=635a8a86cbe21a00013679c5&access_token=10e37f897cce44a884a2eb15616a2682] [XiaohongshuFeignProvider#productGet(String,String,XhsProductGetRequestDto)]: [{"error_code":500,"error_msg":"Request failed, please contact our system administrator 请求失败, 请和系统管理人员联系","success":false}]] with root cause

feign.FeignException$InternalServerError: [500 Internal Server Error] during [POST] to [https://miniapp.xiaohongshu.com/api/rmp/mp/deal/product/get?appid=635a8a86cbe21a00013679c5&access_token=10e37f897cce44a884a2eb15616a2682] [XiaohongshuFeignProvider#productGet(String,String,XhsProductGetRequestDto)]: [{"error_code":500,"error_msg":"Request failed, please contact our system administrator 请求失败, 请和系统管理人员联系","success":false}]
	at feign.FeignException.serverErrorStatus(FeignException.java:231) ~[feign-core-10.12.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:180) ~[feign-core-10.12.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:169) ~[feign-core-10.12.jar:na]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[feign-core-10.12.jar:na]
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[feign-core-10.12.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[feign-core-10.12.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-10.12.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-10.12.jar:na]
	at com.sun.proxy.$Proxy152.productGet(Unknown Source) ~[na:na]
	at com.geely.tiktokminiprogramadmin.http.XhsClient.productGet(XhsClient.java:155) ~[classes/:na]
	at com.geely.tiktokminiprogramadmin.controller.XhsProductController.getProductFromxhs(XhsProductController.java:127) ~[classes/:na]
	at com.geely.tiktokminiprogramadmin.controller.XhsProductController$$FastClassBySpringCGLIB$$e2426d6f.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.7.jar:5.3.7]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.7.jar:5.3.7]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.7.jar:5.3.7]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.7.jar:5.3.7]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.7.jar:5.3.7]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.7.jar:5.3.7]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.7.jar:5.3.7]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.7.jar:5.3.7]
	at com.geely.tiktokminiprogramadmin.controller.XhsProductController$$EnhancerBySpringCGLIB$$27da3d29.getProductFromxhs(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.46.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.46.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.7.jar:5.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.7.jar:5.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.5.0.jar:2.5.0]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.7.jar:5.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.7.jar:5.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by wdvxdr** [comment]
麻烦提供一下请求失败的完整http请求

**Comment by houleeway** [comment]
> 麻烦提供一下请求失败的完整http请求

https://miniapp.xiaohongshu.com/api/rmp/mp/deal/product/get?appid=635a8a86cbe21a00013679c5&access_token=10e37f897cce44a884a2eb15616a2682
